### ISSUE TITLE
text box in group 2(matrixb) are not looped in right order

### ISSUE THREAD

**Issue by eli6462** [eli6462/math101#2]
text box in group 2(matrixb) are not looped in right order - using the initMatrix function

**Comment by sashachernin** [comment]
im on it

**Comment by eli6462** [comment]
I solved it using the new "initMatrixTEST" function, 
Description of the new function :
"a nested loop that checks what is the name of the current textbox, 
and assigns textbox value to matching ""arr2d"" element."

// the new problem - the algorithm may have too big of a Big O complication (I'm not sure about that)

Question: what do you think of the new algorithm complication ? considering it will be used on 9 x 9 matrices and there might be a few of them ?

Also:  this algorithm will probably be used for printing the result into the result matrix.
